"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "../globals.css";
import { SessionProvider } from "next-auth/react";

import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

import Sidebar from "@/layout/admin/sidebar";
import Footer from "@/layout/user/footer";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionProvider>
          <Sidebar>{children}</Sidebar>

          <SpeedInsights />
        </SessionProvider>
      </body>
    </html>
  );
}
